# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: rest
generate:
  client: true
  models: true
output: ../rest/rest.go
output-options:
  client-type-name: Client